### ISSUE TITLE
Epidemiologist

### ISSUE THREAD

**Issue by adamloeffen** [MinecraftCitiesNetwork/Bugs#21]
### Modified:
- line 181 of `home/plugins/DiscordSRV/config.yml`
  - from
```
DiscordChatChannelRoleAliases: {"Owner": "&7[&#9D50BBS&#914EB7t&#864CB3a&#7A4AAEf&#6E48AAf&7]", "Server": "&#bdc3c7Citizen&#bdc3c7", "Attorney General": "&#00aaffAttorney General", "Homeland Department": "&#00aaffHomeland Employee&#bdc3c7", "State Department": "&#00aaffState Employee&#bdc3c7", "Construction & Transport Department": "&#00aaffConstruction Employee&#bdc3c7", "Health Department": "&#00aaffHealth Employee&#bdc3c7", "Education & Commerce Department": "&#00aaffCommerce Employee&#bdc3c7", "Public Affairs Department": "&#00aaffPubl. Affairs Employee&#bdc3c7", "Environment & Recreation Department": "&#00aaffEnvironment Employee&#bdc3c7", "Donator": "&#38ef7dDonator", "Moderator": "&7[&#D25286S&#C65299t&#B952ACa&#AD52BEf&#A052D1f&7]", "Senior Administrator": "&7[&#9D50BBS&#914EB7t&#864CB3a&#7A4AAEf&#6E48AAf&7]", "Presidential Family": "&9Presidential Family&#bdc3c7", "President": "&#7070ffPresident&7", "Secretary": "&#00AAAASecretary&#bdc3c7", "Trainee Officer": "&#00aaffTrainee Officer", "Informant": "&#1cefffInformant", "Constable": "&#00aaffConstable", "Senior Constable": "&#00aaffSenior Constable", "Sergeant": "&#00aaffSergeant", "Representative": "&7[&8Rep&7]", "Doctor": "&fDoctor", "Trainee Doctor": "&fTrainee Doctor", "Medical Specialist": "&#00aaffMedical Specialist",  "Ranger": "&#00aaffRanger", "Senior Ranger": "&#00aaffSenior Ranger", "Administrator": "[&#9D50BBS&#914EB7t&#864CB3a&#7A4AAEf&#6E48AAf&7]", "Chief Justice": "&6Chief Justice", "Judge": "&6Judge", "Magistrate": "&6Magistrate", "representative.congress": "794280510024974346", "Developer": "&7[&#A70505S&#A00606t&#990707a&#910808f&#8A0909f&7]"}
```
  - to 
```
DiscordChatChannelRoleAliases: {"Owner": "&7[&#9D50BBS&#914EB7t&#864CB3a&#7A4AAEf&#6E48AAf&7]", "Server": "&#bdc3c7Citizen&#bdc3c7", "Attorney General": "&#00aaffAttorney General", "Homeland Department": "&#00aaffHomeland Employee&#bdc3c7", "State Department": "&#00aaffState Employee&#bdc3c7", "Construction & Transport Department": "&#00aaffConstruction Employee&#bdc3c7", "Health Department": "&#00aaffHealth Employee&#bdc3c7", "Education & Commerce Department": "&#00aaffCommerce Employee&#bdc3c7", "Public Affairs Department": "&#00aaffPubl. Affairs Employee&#bdc3c7", "Environment & Recreation Department": "&#00aaffEnvironment Employee&#bdc3c7", "Donator": "&#38ef7dDonator", "Moderator": "&7[&#D25286S&#C65299t&#B952ACa&#AD52BEf&#A052D1f&7]", "Senior Administrator": "&7[&#9D50BBS&#914EB7t&#864CB3a&#7A4AAEf&#6E48AAf&7]", "Presidential Family": "&9Presidential Family&#bdc3c7", "President": "&#7070ffPresident&7", "Secretary": "&#00AAAASecretary&#bdc3c7", "Trainee Officer": "&#00aaffTrainee Officer", "Informant": "&#1cefffInformant", "Constable": "&#00aaffConstable", "Senior Constable": "&#00aaffSenior Constable", "Sergeant": "&#00aaffSergeant", "Representative": "&7[&8Rep&7]", "Doctor": "&fDoctor", "Trainee Doctor": "&fTrainee Doctor", "Medical Specialist": "&#00aaffMedical Specialist", "Epidemiologist": "&#00aaffEpidemiologist", "Ranger": "&#00aaffRanger", "Senior Ranger": "&#00aaffSenior Ranger", "Administrator": "[&#9D50BBS&#914EB7t&#864CB3a&#7A4AAEf&#6E48AAf&7]", "Chief Justice": "&6Chief Justice", "Judge": "&6Judge", "Magistrate": "&6Magistrate", "representative.congress": "794280510024974346", "Developer": "&7[&#A70505S&#A00606t&#990707a&#910808f&#8A0909f&7]"}
```

- line 147 of `home/plugins/DiscordSRV/synchronization.yml`
  - inserted `"healthdept.epidemiologist": "1259368867763847302",`

- line 10 of `home/plugins/DeluxeMenus/gui_menus/Info/Jobs/Government Departments/info-jobs-department-of-health.yml`
  - inserted
```
'health-epidemiologist':
    material: hdb-9594
    slot: 0
    priority: 1
    display_name: '&#00aaffEpidemiologist'
    hide_effects: true
    lore:
        - '&#00aaffClick&#bdc3c7 to select this job'
        - '&#bdc3c7to display in chat!'
    left_click_commands:
    - '[console] lp user %player_name% meta setprefix "<#00aaff>Epidemiologist"'
    - '[console] lp user %player_name% meta setsuffix "&#32afedEP"'
    - '[message] &aYour job prefix has been set, say hello!'
    - '[close]'
    view_requirement:
      requirements:
        is_applicable_player:
          type: string equals ignorecase
          input: '%player_name%'
          output: '{username}'
        excludes_conflicting_groups:
          type: "!has permission"
          permission: setdisplayjob.exclude
        has_group:
          type: string equals ignorecase
          input: '%parseother_{{username}}_{player_has_permission_group.epidemiologist}%'
          output: 'yes'
  'health-epidemiologist-manage':
    material: hdb-9594
    slot: 0
    priority: 2
    display_name: '&#00aaffEpidemiologist'
    hide_effects: true
    lore:
        - '&#00aaff&lLEFT CLICK &fto &ahire &f{username}!'
        - '&#00aaff&lRIGHT CLICK &fto &cfire &f{username}!'
        - '&#00aaff&lSHIFT RIGHT CLICK &fto &creject &f{username}!'
    shift_right_click_commands:
    - '[player] mail send {username} &#00aaff&lDOH &7» &fUnfortunately, your application for &#00aaffEpidemiologist &fhas been &cdenied &fat this time.'
    - '[close]'
    left_click_commands:
    - '[console] lp user {username} parent add epidemiologist'
    - '[message] &a{username} has been hired!'
    - '[player] mail send {username} &#00aaff&lDOH &7» &fYou have been &ahired &fas a &#00aaffEpidemiologist&f!'
    - '[close]'
    right_click_commands:
    - '[console] lp user {username} parent remove epidemiologist'
    - '[message] &c{username} has been fired!'
    - '[player] mail send {username} &#00aaff&lDOH &7» &fYou have been &cfired &fas a &#00aaffEpidemiologist&f!'
    - '[close]'    
    view_requirement:
      requirements:
        has_applicable_permissions:
          type: has permission
          permission: group.healthsec
```
  - Modifed the material, and slot of each item on the list accordingly.

### Footnotes
- Created LP group "epidemiologist" with priority `56` and set prefix and suffix of the group accordingly
- Created epidemiologist role on discord, and used the role id for the DiscordSRV stuff
