### ISSUE TITLE
Request a ranger not showing.

### ISSUE THREAD

**Issue by taylorhaight** [MinecraftCitiesNetwork/Bugs#60]
When someone goes to the animal shelter and requests a ranger, it tells them that a ranger has been alerted but rangers never get an announcement for it.

**Comment by Technofied** [comment]
Anyone's game :)

**Comment by adamloeffen** [comment]
**Issue:** 
>When someone goes to the animal shelter and requests a ranger, it tells them that a ranger has been alerted but rangers never get an announcement for it.

**Notes:** The Department of Health also has a `/request-a-doctor` command that works in the same way, however it does broadcast messages to DOH staff as it should.

**Solution:** Delete the different `/request-ranger` commands in `home/plugins/MyCommand/commands/department_of_the_interior.yml` (see below) and replace them with a singular command mirroring the format in the `.../department_of_health.yml` file.


**Original File:**
```
# line 88 - 176
request-ranger-oakridge:
  command: /request-ranger-oakridge
  type:
  - RUN_COMMAND
  - BROADCAST_TEXT
  text:
  - "$hex%#00AAFF%&lD$hex%#009CFF%&lO$hex%#008EFF%&lI &l$hex%#bdc3c7%» &c$player requires assistance at the &fOakridge Animal Shelter!"
  runcmd:
  - "$RUN_CONSOLE$/send $player $hex%#00AAFF%&lD$hex%#009CFF%&lO$hex%#008EFF%&lI &l$hex%#bdc3c7%» All online rangers have been called to assist you!"
  cooldown: 60
  permission-required: false
  cooldown-message: '$hex%#00AAFF%&lD$hex%#009CFF%&lE$hex%#008EFF%&lR &l$hex%#bdc3c7%» You have already called for a Ranger! Please wait patiently.'
  broadcast_message_permission_node: group.ranger    
  register: true

request-ranger-willow:
  command: /request-ranger-willow
  type:
  - RUN_COMMAND
  - BROADCAST_TEXT
  text:
  - "$hex%#00AAFF%&lD$hex%#009CFF%&lO$hex%#008EFF%&lI &l$hex%#bdc3c7%» &c$player requires assistance at the &fWillow Animal Shelter!"
  runcmd:
  - "$RUN_CONSOLE$/send $player $hex%#00AAFF%&lD$hex%#009CFF%&lO$hex%#008EFF%&lI &l$hex%#bdc3c7%» All online rangers have been called to assist you!"
  cooldown: 60
  permission-required: false
  cooldown-message: "$hex%#00AAFF%&lD$hex%#009CFF%&lO$hex%#008EFF%&lI &l$hex%#bdc3c7%» You have already called for a Ranger! Please wait patiently."
  broadcast_message_permission_node: group.ranger  
  register: true

request-ranger-aventura:
  command: /request-ranger-aventura
  type:
  - RUN_COMMAND
  - BROADCAST_TEXT
  text:
  - '$hex%#00AAFF%&lD$hex%#009CFF%&lO$hex%#008EFF%&lI &l$hex%#bdc3c7%» &c$player requires assistance at the &fAventura Animal Shelter!'
  runcmd:
  - "$RUN_CONSOLE$/send $player $hex%#00AAFF%&lD$hex%#009CFF%&lO$hex%#008EFF%&lI &l$hex%#bdc3c7%» All online rangers have been called to assist you!"
  cooldown: 60
  permission-required: false
  cooldown-message: "$hex%#00AAFF%&lD$hex%#009CFF%&lO$hex%#008EFF%&lI &l$hex%#bdc3c7%» You have already called for a Ranger! Please wait patiently."
  broadcast_message_permission_node: group.ranger    
  register: true

request-ranger-hamilton:
  command: /request-ranger-hamilton
  type:
  - RUN_COMMAND
  - BROADCAST_TEXT
  text:
  - "$hex%#00AAFF%&lD$hex%#009CFF%&lO$hex%#008EFF%&lI &l$hex%#bdc3c7%» &c$player requires assistance at the &fHamilton City Animal Shelter!"
  runcmd:
  - "$RUN_CONSOLE$/send $player $hex%#00AAFF%&lD$hex%#009CFF%&lO$hex%#008EFF%&lI &l$hex%#bdc3c7%» All online rangers have been called to assist you!"
  cooldown: 60
  permission-required: false
  cooldown-message: '$hex%#00AAFF%&lD$hex%#009CFF%&lO$hex%#008EFF%&lI &l$hex%#bdc3c7%» You have already called for a Ranger! Please wait patiently.'
  broadcast_message_permission_node: group.ranger
  register: true
  
request-ranger-klondike:
  command: /request-ranger-klondike
  type:
  - RUN_COMMAND
  - BROADCAST_TEXT
  text:
  - "$hex%#00AAFF%&lD$hex%#009CFF%&lO$hex%#008EFF%&lI &l$hex%#bdc3c7%» &c$player requires assistance at the &fKlondike Animal Shelter!"
  runcmd:
  - "$RUN_CONSOLE$/send $player $hex%#00AAFF%&lD$hex%#009CFF%&lO$hex%#008EFF%&lI &l$hex%#bdc3c7%» All online rangers have been called to assist you!"
  cooldown: 60
  permission-required: false
  cooldown-message: "$hex%#00AAFF%&lD$hex%#009CFF%&lE$hex%#008EFF%&lR &l$hex%#bdc3c7%» You have already called for a Ranger! Please wait patiently."
  broadcast_message_permission_node: group.ranger  
  register: true
  
request-ranger-reveille:
  command: /request-ranger-reveille
  type:
  - RUN_COMMAND
  - BROADCAST_TEXT
  text:
  - "$hex%#00AAFF%&lD$hex%#009CFF%&lO$hex%#008EFF%&lI &l$hex%#bdc3c7%» &c$player requires assistance at the &fReveille Animal Shelter!"
  runcmd:
  - "$RUN_CONSOLE$/send $player $hex%#00AAFF%&lD$hex%#009CFF%&lO$hex%#008EFF%&lI &l$hex%#bdc3c7%» All online rangers have been called to assist you!"
  cooldown: 60
  permission-required: false
  cooldown-message: "$hex%#00AAFF%&lD$hex%#009CFF%&lO$hex%#008EFF%&lI &l$hex%#bdc3c7%» You have already called for a Ranger! Please wait patiently."
  broadcast_message_permission_node: group.ranger 
  register: true
```

**Modified file:**
```
# starting at line 88
request-a-ranger:
  command: /request-a-ranger
  type:
  - RUN_COMMAND
  runcmd:
  - '$broadcasttext$$hex%#00AAFF%&lD$hex%#009CFF%&lO$hex%#008EFF%&lI $hex%#bdc3c7%» &c$player has required assistance at the &f$multiargs&c!'
  - '$mm$<gradient:#00AAFF:#008EFF><bold>DOI</bold> <grey>» All online rangers have been called to assist you!'
  cooldown: 60
  permission-required: false
  cooldown-message: "$hex%#00AAFF%&lD$hex%#009CFF%&lO$hex%#008EFF%&lI &l$hex%#bdc3c7%» You have already called for a Ranger! Please wait patiently."
  broadcast_message_permission_node: democracy.ranger
  register: true
```

**Footnotes:** To set up the different shelter locations, should this be implemented, admin+ will have to use the same process required to add the DOH monitors (specifying location in command argument).

**Edit:** Apparently $broadcasttext$ doesn't work with minimessage formatting so switched to hex formatting for that line... a learning moment :>
