### ISSUE TITLE
Jungle and Birch Logs can be turned into unrelated blocks

### ISSUE THREAD

**Issue by adamloeffen** [MinecraftCitiesNetwork/Bugs#67]
Reported by @Sergecool

> hey idk if its a bug you guys know about or not but when changing birch logs to planks u get copper blocks...
> and for some reason jungle logs wont even turn into planks or anything else.. and i need them planks lol.
> other logs seem fine..

As of now, we know that birch logs will only become copper when placed in the upper left corner, and jungle logs will only become planks when placed in the middle left slot. 

A temp fix was found in `home/plugins/ItemsAdder/contents/_iainternal/configs/food/general_food.yml`
```
jungle_log_fix:
      permission: general.recipes
      enabled: true
      pattern:
      - XXX
      - AXX
      - XXX
      ingredients:
        A: JUNGLE_LOG
      result:
        item: JUNGLE_PLANKS
        amount: 4
```
