### ISSUE TITLE
/doi-attend warp corrections

### ISSUE THREAD

**Issue by adamloeffen** [MinecraftCitiesNetwork/Bugs#76]
**Issue:** The Town of Oakridge moved their Animal Shelter meaning that the warp used by the command `/doi-attend` isn't accurate anymore.
**Solution:** I deleted the oakridgeshelter warp and recreated it in the correct place.
**Notes:** While I was doing this, I noticed that the GUI itself was severely outdated referencing the "Klondike Shelter" (coming soon 💀). Therefore, I modified the GUI (`home/plugins/DeluxeMenus/gui_menus/rangermenu.yml`).

**Original File:**
```
menu_title: '&3Animal Shelter Menu'
open_commands:
  - '[sound] BLOCK_BEACON_ACTIVATE'
size: 9
items:
  'Reveille':
    material: NETHER_STAR
    slot: 2
    display_name: '&3Reveille Shelter'
    lore:
      - '&fRanger Duties Only!'
      - '&4Abuse = Termination'
      - '&cWarps logs actively monitored'
    view_requirement:
      requirements:
        ranger:
          type: has permission
          permission: democracy.ranger
    left_click_commands:
      - '[console] essentials:warp reveilleshelter %player_name%'
  'Reveille Willow':
    material: NETHER_STAR
    slot: 3
    display_name: '&3Willow Shelter'
    lore:
      - '&fRanger Duties Only!'
      - '&4Abuse = Termination'
      - '&cWarps logs actively monitored'
    view_requirement:
      requirements:
        ranger:
          type: has permission
          permission: democracy.ranger
    left_click_commands:
      - '[console] essentials:warp willowshelter %player_name%'
  'Reveille Aventura':
    material: NETHER_STAR
    slot: 4
    display_name: '&3Aventura Shelter'
    lore:
      - '&fComing soon'
    view_requirement:
      requirements:
        ranger:
          type: has permission
          permission: democracy.ranger
  'Reveille Klondike':
    material: NETHER_STAR
    slot: 5
    display_name: '&3Klondike Shelter'
    lore:
      - '&fComing soon'
    view_requirement:
      requirements:
        ranger:
          type: has permission
          permission: democracy.ranger
  'gravel':
    material: NETHER_STAR
    slot: 6
    display_name: '&3Oakridge Shelter'
    lore:
      - '&fRanger Duties Only!'
      - '&4Abuse = Termination'
      - '&cWarps logs actively monitored'
    view_requirement:
      requirements:
        ranger:
          type: has permission
          permission: democracy.ranger
    left_click_commands:
      - '[console] essentials:warp oakridgeshelter %player_name%'
```

**Modified File:**
```
menu_title: '&3Animal Shelter Menu'
open_commands:
  - '[sound] BLOCK_BEACON_ACTIVATE'
size: 9
items:
  'Reveille':
    material: NETHER_STAR
    slot: 2
    display_name: '&3Reveille Shelter'
    lore:
      - '&fRanger Duties Only!'
      - '&4Abuse = Termination'
      - '&cWarps logs actively monitored'
    view_requirement:
      requirements:
        ranger:
          type: has permission
          permission: democracy.ranger
    left_click_commands:
      - '[console] essentials:warp reveilleshelter %player_name%'
  'Reveille Willow':
    material: NETHER_STAR
    slot: 3
    display_name: '&3Willow Shelter'
    lore:
      - '&fRanger Duties Only!'
      - '&4Abuse = Termination'
      - '&cWarps logs actively monitored'
    view_requirement:
      requirements:
        ranger:
          type: has permission
          permission: democracy.ranger
    left_click_commands:
      - '[console] essentials:warp willowshelter %player_name%'
  'DOI Divider':
    material: hdb-16659
    slot: 4
    display_name: '&3&lRaccoon'
    hide_effects: true
  'Reveille Aventura':
    material: NETHER_STAR
    slot: 5
    display_name: '&3Aventura Shelter'
    lore:
      - '&fComing soon'
    view_requirement:
      requirements:
        ranger:
          type: has permission
          permission: democracy.ranger
  'Reveille Oakridge':
    material: NETHER_STAR
    slot: 6
    display_name: '&3Oakridge Shelter'
    lore:
      - '&fRanger Duties Only!'
      - '&4Abuse = Termination'
      - '&cWarps logs actively monitored'
    view_requirement:
      requirements:
        ranger:
          type: has permission
          permission: democracy.ranger
    left_click_commands:
      - '[console] essentials:warp oakridgeshelter %player_name%'
```
