### ISSUE TITLE
Hospital Warp Command

### ISSUE THREAD

**Issue by adamloeffen** [MinecraftCitiesNetwork/Bugs#81]
**Issue:** New command requested by Department of Health Secretary for MS+ to be able to teleport to the different hospitals and clinics to restock/solve any disputes at the DOH sites.

**Solution:** Created a DeluxeMenu ( because they look nice :P ) to allow players to select the different sites and then added a command to `home/plugins/MyCommand/commands/department_of_health.yml` to be able to use the menu.

**New File:**
```
# located at home/plugins/DeluxeMenus/gui_menus/hospitalwarpmenu.yml

menu_title: '&3Hospital Warp Menu'
open_commands:
  - '[sound] BLOCK_BEACON_ACTIVATE'
size: 9

items:
  'Reveille':
    material: NETHER_STAR
    slot: 1
    display_name: '&3Reveille Main Hospital'
    lore:
      - '&fMS Duties Only!'
      - '&4Abuse = Termination'
      - '&cWarps logs actively monitored'
    left_click_commands:
      - '[console] essentials:warp hospitalreveille %player_name%'
  'South':
    material: NETHER_STAR
    slot: 2
    display_name: '&3Westminister Hospital'
    lore:
      - '&fMS Duties Only!'
      - '&4Abuse = Termination'
      - '&cWarps logs actively monitored'
    left_click_commands:
      - '[console] essentials:warp hospitalsouth %player_name%'
  'University':
    material: NETHER_STAR
    slot: 3
    display_name: '&3University Hospital'
    lore:
      - '&fMS Duties Only!'
      - '&4Abuse = Termination'
      - '&cWarps logs actively monitored'
    left_click_commands:
      - '[console] essentials:warp hospitaluni %player_name%'
  'Placeholder':
    material: hdb-35114
    slot: 4
    display_name: '&3&lHospital Warps'
    hide_effects: true
  'Claremont':
    material: NETHER_STAR
    slot: 5
    display_name: '&3Claremont Clinic'
    lore:
      - '&fMS Duties Only!'
      - '&4Abuse = Termination'
      - '&cWarps logs actively monitored'
    left_click_commands:
      - '[console] essentials:warp hospitalclaremont %player_name%'
  'Oakridge':
    material: NETHER_STAR
    slot: 5
    display_name: '&3Oakridge Clinic'
    lore:
      - '&fMS Duties Only!'
      - '&4Abuse = Termination'
      - '&cWarps logs actively monitored'
    left_click_commands:
      - '[console] essentials:warp hospitaloakridge %player_name%'
  'Aventura':
    material: NETHER_STAR
    slot: 6
    display_name: '&3Adventura Clinic'
    lore:
      - '&fMS Duties Only!'
      - '&4Abuse = Termination'
      - '&cWarps logs actively monitored'
    left_click_commands:
      - '[console] essentials:warp hospitalaventura %player_name%'
```

**Modified File:**
```
# DOH mycommand file added at line 193

doh-warp:
  command: /doh-warp
  type:
  - RUN_COMMAND
  runcmd:
  - '$RUN_CONSOLE$/dm open medspecmenu  %player_name%'
  - '&RUN_CONSOLE$discordsrv:discord broadcast ##hospital-warps > :calling: ** %player_name% is now warping to the $arg1 Hospital for $multiargs!**'
  permission-required: true
  permission-node: doh.medicalspecalist
  register: true
  required_args: 2
  tab_completer:
    1:
    - Reveille
    - Westminister
    - University
    - Claremont
    - Oakridge
    - Aventura
```

**Comment by adamloeffen** [comment]
**Note:** As it turns out, this appears to be a previous feature for all doctors until the new `/doctor-attend` system was set up. The `doctormenu.yml` in the same directory proved it. The above config (which was in the `hospitalwarpsmenu.yml` file) has been pasted in the old `doctormenu.yml` and it has been renamed `medspecmenu.yml`. The other file has been deleted. For transparency the original config from that file has been pasted below. The mycommand has been updated to reflect this.

**doctormenu.yml:**
```
menu_title: '&3Hospital Menu'
open_command: doctor-tp
open_commands:
  - '[sound] BLOCK_BEACON_ACTIVATE'
size: 8
register_command: true
args:
- username
open_requirement:
  requirements:
    permission_d:
      type: string equals
      input: '%mycommand_playerdatafor_[{username}]_canusemedicare%'
      output: '%player_name%'
      deny_commands:
        - '[message] &cYou don''t have permission to do that!'
items:
  reveille:
    material: NETHER_STAR
    slot: 1
    display_name: '&3Main Reveille Hospital'
    lore:
      - '&fDoctor Duties Only!'
      - '&4Abuse = Termination'
      - '&cWarps logs actively monitored'
    view_requirement:
      requirements:
        ranger:
          type: has permission
          permission: democracy.doctor
    left_click_commands:
      - '[console] essentials:warp hospitalreveille %player_name% '
  university-hospital:
    material: NETHER_STAR
    slot: 2
    display_name: '&3University Hospital'
    lore:
      - '&fDoctor Duties Only!'
      - '&4Abuse = Termination'
      - '&cWarps logs actively monitored'
    view_requirement:
      requirements:
        ranger:
          type: has permission
          permission: democracy.doctor
    left_click_commands:
      - '[console] essentials:warp hospitaluni %player_name% '
  Claremont':
    material: NETHER_STAR
    slot: 3
    display_name: '&3Claremont Reveille Hospital'
    lore:
      - '&fDoctor Duties Only!'
      - '&4Abuse = Termination'
      - '&cWarps logs actively monitored'
    view_requirement:
      requirements:
        ranger:
          type: has permission
          permission: democracy.doctor
    left_click_commands:
      - '[console] essentials:warp hospitalclaremont %player_name%'
  South':
    material: NETHER_STAR
    slot: 4
    display_name: '&3South Reveille Hospital'
    lore:
      - '&fDoctor Duties Only!'
      - '&4Abuse = Termination'
      - '&cWarps logs actively monitored'
    view_requirement:
      requirements:
        ranger:
          type: has permission
          permission: democracy.doctor
    left_click_commands:
      - '[console] essentials:warp hospitalsouth %player_name%'
  Oakridge:
    material: NETHER_STAR
    slot: 5
    display_name: '&3Oakridge Health Clinic'
    lore:
      - '&fDoctor Duties Only!'
      - '&4Abuse = Termination'
      - '&cWarps logs actively monitored'
    view_requirement:
      requirements:
        ranger:
          type: has permission
          permission: democracy.doctor
    left_click_commands:
      - '[console] essentials:warp hospitaloakridge %player_name%'
  Aventura:
    material: NETHER_STAR
    slot: 6
    display_name: '&3Aventura Health Clinic'
    lore:
      - '&fDoctor Duties Only!'
      - '&4Abuse = Termination'
      - '&cWarps logs actively monitored'
    view_requirement:
      requirements:
        ranger:
          type: has permission
          permission: democracy.doctor
    left_click_commands:
      - '[console] essentials:warp hospitalaventura %player_name%'
  Willow:
    material: NETHER_STAR
    slot: 7
    display_name: '&3Willow Health Clinic'
    lore:
      - '&fDoctor Duties Only!'
      - '&4Abuse = Termination'
      - '&cWarps logs actively monitored'
    view_requirement:
      requirements:
        ranger:
          type: has permission
          permission: democracy.doctor
    left_click_commands:
      - '[console] essentials:warp hospitalwillow %player_name%'
```
